# Generated by Django 2.0.6 on 2018-10-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='transaction_date',
            field=models.CharField(blank=True, max_length=30, verbose_name='Trans. Date'),
        ),
    ]
