# Generated by Django 2.0.6 on 2018-10-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20181007_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='transaction_amount',
            field=models.CharField(blank=True, max_length=30, verbose_name='Amount'),
        ),
    ]
