# Generated by Django 2.0.6 on 2018-10-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20181007_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='category',
            field=models.CharField(max_length=30, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='description',
            field=models.CharField(max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='post_date',
            field=models.CharField(max_length=30, verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='transaction_amount',
            field=models.CharField(max_length=30, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='transaction_date',
            field=models.CharField(max_length=30, verbose_name='date'),
        ),
    ]
