# Generated by Django 2.0.6 on 2018-10-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_auto_20181008_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='post_date',
            field=models.CharField(max_length=30, verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='transaction_amount',
            field=models.CharField(max_length=30, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='transaction_date',
            field=models.CharField(max_length=30, verbose_name='date'),
        ),
    ]
