# Generated by Django 2.0.6 on 2018-10-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20181008_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='transaction_date',
            field=models.DateField(max_length=30, verbose_name='date'),
        ),
    ]
