# Generated by Django 2.0.6 on 2018-10-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_auto_20181008_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='transaction_date',
            field=models.DateField(max_length=30, null=True, verbose_name='date'),
        ),
    ]
