# Generated by Django 2.0.6 on 2018-10-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_auto_20181008_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankstatement',
            old_name='transaction_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='bankstatement',
            old_name='transaction_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='bankstatement',
            old_name='post_date',
            new_name='post',
        ),
    ]
