# Generated by Django 2.0.6 on 2018-10-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_auto_20181008_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='date',
            field=models.DateField(max_length=30, null=True, verbose_name='Trans. Date'),
        ),
    ]
