# Generated by Django 2.0.6 on 2018-10-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_auto_20181008_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='amount',
            field=models.CharField(max_length=30, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='category',
            field=models.CharField(max_length=30, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='post',
            field=models.CharField(max_length=30, verbose_name='Post Date'),
        ),
    ]
