# Generated by Django 2.0.6 on 2018-10-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0012_auto_20181009_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='bank_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
