# Generated by Django 2.0.6 on 2018-10-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0014_auto_20181021_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankstatementdocument',
            old_name='title',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='bankstatementdocument',
            name='slug',
            field=models.SlugField(blank=True, help_text='A label for bank statment doc.', max_length=63, unique=True),
        ),
    ]
