# Generated by Django 2.0.6 on 2018-10-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0016_remove_bankstatementdocument_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatementdocument',
            name='bank',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bankstatementdocument',
            name='owner',
            field=models.CharField(max_length=255),
        ),
    ]
