# Generated by Django 2.0.6 on 2018-10-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0018_remove_bankstatementdocument_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatementdocument',
            name='bank',
            field=models.CharField(max_length=255),
        ),
    ]
