# Generated by Django 2.0.6 on 2018-10-21 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0024_auto_20181021_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='owner',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='statement_source',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bankstatementdocument',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 21, 21, 41, 45, 572857), editable=False),
        ),
    ]
