# Generated by Django 2.0.6 on 2018-10-23 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0026_auto_20181021_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='slug',
            field=models.SlugField(blank=True, max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name='bankstatementdocument',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 23, 21, 45, 28, 477762), editable=False),
        ),
    ]
