# Generated by Django 2.0.6 on 2018-10-23 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0027_auto_20181023_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatementdocument',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 23, 21, 46, 33, 962616), editable=False),
        ),
    ]
