# Generated by Django 2.0.6 on 2018-10-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0030_auto_20181023_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='slug',
            field=models.CharField(blank=True, max_length=63),
        ),
    ]
