# Generated by Django 2.0.6 on 2018-10-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0031_auto_20181023_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankstatement',
            name='slug',
        ),
    ]
