# Generated by Django 2.0.6 on 2018-10-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0033_bankstatement_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='slug',
            field=models.SlugField(blank=True, max_length=63, unique=True),
        ),
    ]
