# Generated by Django 2.0.6 on 2018-10-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0037_auto_20181024_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='slug',
            field=models.SlugField(max_length=63, unique=True),
        ),
    ]
